name: Hugo自动构建部署
on:
  push:
    branches: [ main ]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码（包含主题子模块）
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: 安装Hugo扩展版
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true
      - name: 构建静态网站
        run: hugo --gc --minify
      - name: 部署到Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public